imx8mp-var-dart: Fix MIPI CSI-1 endpoint configuration
Partially revert b4cc21c97936: imx8mp-var-dart: align mipi_csi nodes with NXP

The MIPI interface was failing to allocate memory  and negotiate streaming
parameters due to a missing `reg` property in  the `port` node from the
mipi_csi_1, causing conflicts between MIPI CSI-0 and MIPI CSI-1 data.
Without this, the CSI interface could not establish a  proper link with
the OV5640 sensor, leading to errors in GStreamer:

  ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
  	 Failed to allocate required memory.
         Buffer pool activation failed
  ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
         Internal data stream error.

This patch updates the `mipi_csi_1` node to use `port@1` with `reg = <1>`,
linking it to the remote endpoint properly.

Signed-off-by: Alifer Moraes <alifer.m@variscite.com>